public enum BuildingType
{
    Source,
    Portal,
    ArcherFortress,
    MageTower,
    RockTower,
    Lumbermill,
    LightningTower,
    FireTower,
    EarthTower,
    StoneMine,
    ArcherTower,
    CrystalAccelerator,
    FrigidShard,
    Farm,
    Forager,
    House
}