public enum BuildingType
{
    ArcherFortress,
    LightningTower,
    FireTower,
    EarthTower,
    ArcherTower,
    CrystalAccelerator,
    FrigidShard,
    SparkTower,
    ChainLightningTower,
    MeteorTower,
    Spikes,
    FlamethrowerTower,
    House,
    GuardTower,
    Dock,
    Orb
}